// Massive Database: 100 Movies
const database = [
    // --- HOLLYWOOD ---
    { id: 1, title: "Inception", genres: ["Action", "Sci-Fi", "Thriller"], rating: 8.8 },
    { id: 2, title: "The Matrix", genres: ["Action", "Sci-Fi"], rating: 8.7 },
    { id: 3, title: "Interstellar", genres: ["Drama", "Sci-Fi"], rating: 8.6 },
    { id: 4, title: "The Hangover", genres: ["Comedy"], rating: 7.7 },
    { id: 5, title: "Superbad", genres: ["Comedy"], rating: 7.6 },
    { id: 6, title: "The Notebook", genres: ["Drama", "Romance"], rating: 7.8 },
    { id: 7, title: "Titanic", genres: ["Drama", "Romance"], rating: 7.9 },
    { id: 8, title: "Die Hard", genres: ["Action", "Thriller"], rating: 8.2 },
    { id: 9, title: "La La Land", genres: ["Comedy", "Drama", "Romance"], rating: 8.0 },
    { id: 10, title: "Mad Max: Fury Road", genres: ["Action", "Sci-Fi"], rating: 8.1 },
    { id: 11, title: "The Dark Knight", genres: ["Action", "Drama", "Thriller"], rating: 9.0 },
    { id: 12, title: "Blade Runner 2049", genres: ["Action", "Sci-Fi", "Thriller"], rating: 8.0 },
    { id: 13, title: "John Wick", genres: ["Action", "Thriller"], rating: 7.4 },
    { id: 14, title: "Jurassic Park", genres: ["Action", "Sci-Fi", "Thriller"], rating: 8.2 },
    { id: 15, title: "The Terminator", genres: ["Action", "Sci-Fi"], rating: 8.1 },
    { id: 16, title: "Alien", genres: ["Sci-Fi", "Thriller"], rating: 8.5 },
    { id: 17, title: "Gladiator", genres: ["Action", "Drama"], rating: 8.5 },
    { id: 18, title: "Avengers: Endgame", genres: ["Action", "Sci-Fi", "Drama"], rating: 8.4 },
    { id: 19, title: "Forrest Gump", genres: ["Drama", "Romance"], rating: 8.8 },
    { id: 20, title: "The Truman Show", genres: ["Comedy", "Drama", "Sci-Fi"], rating: 8.2 },
    { id: 21, title: "Good Will Hunting", genres: ["Drama", "Romance"], rating: 8.3 },
    { id: 22, title: "Pride & Prejudice", genres: ["Drama", "Romance"], rating: 7.8 },
    { id: 23, title: "Crazy, Stupid, Love", genres: ["Comedy", "Drama", "Romance"], rating: 7.4 },
    { id: 24, title: "Step Brothers", genres: ["Comedy"], rating: 6.9 },
    { id: 25, title: "Groundhog Day", genres: ["Comedy", "Romance", "Drama"], rating: 8.1 },
    { id: 26, title: "The Pursuit of Happyness", genres: ["Drama"], rating: 8.0 },
    { id: 27, title: "Parasite", genres: ["Comedy", "Drama", "Thriller"], rating: 8.5 },
    { id: 28, title: "Pulp Fiction", genres: ["Drama", "Thriller"], rating: 8.9 },
    { id: 29, title: "The Martian", genres: ["Sci-Fi", "Drama"], rating: 8.0 },
    { id: 30, title: "Everything Everywhere All at Once", genres: ["Action", "Comedy", "Sci-Fi"], rating: 7.8 },

    // --- BOLLYWOOD: COMEDY ---
    { id: 31, title: "3 Idiots", genres: ["Comedy", "Drama"], rating: 8.4 },
    { id: 32, title: "Hera Pheri", genres: ["Comedy"], rating: 8.1 },
    { id: 33, title: "Munna Bhai M.B.B.S.", genres: ["Comedy", "Drama"], rating: 8.1 },
    { id: 34, title: "Andaz Apna Apna", genres: ["Comedy", "Romance"], rating: 8.0 },
    { id: 35, title: "PK", genres: ["Comedy", "Drama", "Sci-Fi"], rating: 8.1 },
    { id: 36, title: "Lage Raho Munna Bhai", genres: ["Comedy", "Drama"], rating: 8.0 },
    { id: 37, title: "Golmaal: Fun Unlimited", genres: ["Comedy"], rating: 7.5 },
    { id: 38, title: "Dhamaal", genres: ["Comedy"], rating: 7.4 },
    { id: 39, title: "Bhool Bhulaiyaa", genres: ["Comedy", "Thriller"], rating: 7.4 },
    { id: 40, title: "Welcome", genres: ["Comedy", "Romance"], rating: 7.0 },
    { id: 41, title: "Chup Chup Ke", genres: ["Comedy", "Romance"], rating: 6.9 },
    { id: 42, title: "Phir Hera Pheri", genres: ["Comedy"], rating: 7.1 },
    { id: 43, title: "Delhi Belly", genres: ["Comedy", "Action"], rating: 7.6 },
    { id: 44, title: "Khosla Ka Ghosla!", genres: ["Comedy", "Drama"], rating: 8.3 },
    { id: 45, title: "Badhaai Ho", genres: ["Comedy", "Drama"], rating: 7.9 },

    // --- BOLLYWOOD: ROMANCE & DRAMA ---
    { id: 46, title: "Dilwale Dulhania Le Jayenge", genres: ["Romance", "Drama"], rating: 8.0 },
    { id: 47, title: "Jab We Met", genres: ["Romance", "Comedy"], rating: 7.9 },
    { id: 48, title: "Kabhi Khushi Kabhie Gham...", genres: ["Drama", "Romance"], rating: 7.4 },
    { id: 49, title: "Kuch Kuch Hota Hai", genres: ["Romance", "Drama", "Comedy"], rating: 7.5 },
    { id: 50, title: "Veer-Zaara", genres: ["Drama", "Romance"], rating: 7.8 },
    { id: 51, title: "Kal Ho Naa Ho", genres: ["Comedy", "Drama", "Romance"], rating: 7.9 },
    { id: 52, title: "Zindagi Na Milegi Dobara", genres: ["Comedy", "Drama", "Romance"], rating: 8.2 },
    { id: 53, title: "Yeh Jawaani Hai Deewani", genres: ["Romance", "Drama", "Comedy"], rating: 7.2 },
    { id: 54, title: "Dil Chahta Hai", genres: ["Comedy", "Drama", "Romance"], rating: 8.1 },
    { id: 55, title: "Barfi!", genres: ["Comedy", "Drama", "Romance"], rating: 8.1 },
    { id: 56, title: "Aashiqui 2", genres: ["Romance", "Drama"], rating: 7.1 },
    { id: 57, title: "Kabir Singh", genres: ["Action", "Drama", "Romance"], rating: 7.0 },
    { id: 58, title: "Rockstar", genres: ["Drama", "Romance"], rating: 7.7 },
    { id: 59, title: "My Name Is Khan", genres: ["Drama", "Romance"], rating: 7.9 },
    { id: 60, title: "Swades", genres: ["Drama"], rating: 8.2 },
    { id: 61, title: "Taare Zameen Par", genres: ["Drama"], rating: 8.3 },
    { id: 62, title: "Chak De! India", genres: ["Drama", "Action"], rating: 8.1 },
    { id: 63, title: "Bhaag Milkha Bhaag", genres: ["Drama", "Action"], rating: 8.2 },
    { id: 64, title: "Dangal", genres: ["Action", "Drama"], rating: 8.3 },
    { id: 65, title: "Gully Boy", genres: ["Drama"], rating: 7.9 },

    // --- BOLLYWOOD: THRILLER & MYSTERY ---
    { id: 66, title: "Andhadhun", genres: ["Comedy", "Thriller", "Drama"], rating: 8.2 },
    { id: 67, title: "Drishyam", genres: ["Drama", "Thriller"], rating: 8.2 },
    { id: 68, title: "Kahaani", genres: ["Thriller", "Drama"], rating: 8.1 },
    { id: 69, title: "A Wednesday", genres: ["Action", "Drama", "Thriller"], rating: 8.1 },
    { id: 70, title: "Special 26", genres: ["Action", "Comedy", "Thriller"], rating: 8.0 },
    { id: 71, title: "Talaash", genres: ["Thriller", "Drama"], rating: 7.2 },
    { id: 72, title: "Baby", genres: ["Action", "Thriller"], rating: 7.9 },
    { id: 73, title: "Raazi", genres: ["Action", "Drama", "Thriller"], rating: 7.7 },
    { id: 74, title: "Badla", genres: ["Thriller", "Drama"], rating: 7.8 },
    { id: 75, title: "Ittefaq", genres: ["Thriller", "Mystery"], rating: 7.2 },
    { id: 76, title: "Udaan", genres: ["Drama"], rating: 8.1 },
    { id: 77, title: "Haider", genres: ["Action", "Drama", "Thriller"], rating: 8.0 },
    { id: 78, title: "Raman Raghav 2.0", genres: ["Thriller", "Drama"], rating: 7.3 },
    { id: 79, title: "NH10", genres: ["Action", "Thriller", "Drama"], rating: 7.2 },
    { id: 80, title: "Wazir", genres: ["Action", "Thriller", "Drama"], rating: 7.1 },

    // --- BOLLYWOOD: ACTION & SCI-FI ---
    { id: 81, title: "Sholay", genres: ["Action", "Comedy", "Drama"], rating: 8.1 },
    { id: 82, title: "War", genres: ["Action", "Thriller"], rating: 6.5 },
    { id: 83, title: "Pathaan", genres: ["Action", "Thriller"], rating: 5.9 },
    { id: 84, title: "Jawan", genres: ["Action", "Thriller", "Drama"], rating: 7.0 },
    { id: 85, title: "Don", genres: ["Action", "Thriller"], rating: 7.1 },
    { id: 86, title: "Dhoom 2", genres: ["Action", "Thriller"], rating: 6.5 },
    { id: 87, title: "Ek Tha Tiger", genres: ["Action", "Romance", "Thriller"], rating: 6.3 },
    { id: 88, title: "Uri: The Surgical Strike", genres: ["Action", "Drama"], rating: 8.2 },
    { id: 89, title: "Agneepath", genres: ["Action", "Drama"], rating: 6.9 },
    { id: 90, title: "Gangs of Wasseypur", genres: ["Action", "Comedy", "Drama"], rating: 8.2 },
    { id: 91, title: "Koi... Mil Gaya", genres: ["Sci-Fi", "Romance", "Drama"], rating: 7.1 },
    { id: 92, title: "Krrish", genres: ["Action", "Sci-Fi"], rating: 6.4 },
    { id: 93, title: "Ra.One", genres: ["Action", "Sci-Fi"], rating: 4.8 },
    { id: 94, title: "Enthiran (Robot)", genres: ["Action", "Sci-Fi"], rating: 7.1 },
    { id: 95, title: "Brahmastra", genres: ["Action", "Sci-Fi", "Drama"], rating: 5.6 },
    { id: 96, title: "Mr. India", genres: ["Action", "Comedy", "Sci-Fi"], rating: 7.7 },
    { id: 97, title: "Bhavesh Joshi", genres: ["Action", "Drama", "Thriller"], rating: 7.6 },
    { id: 98, title: "Attack", genres: ["Action", "Sci-Fi", "Thriller"], rating: 7.2 },
    { id: 99, title: "Kalki 2898 AD", genres: ["Action", "Sci-Fi", "Drama"], rating: 7.6 },
    { id: 100, title: "Baahubali", genres: ["Action", "Drama"], rating: 8.2 }
].map(movie => {
    // This dynamically creates a guaranteed working cover image using the movie's exact title!
    const encodedTitle = encodeURIComponent(movie.title);
    return {
        ...movie,
        img: `https://placehold.co/400x600/1e1e1e/f5c518?text=${encodedTitle}`
    };
});
